/*
Find the Difference  QuestionEditorial Solution  My Submissions
Total Accepted: 19810
Total Submissions: 39974
Difficulty: Easy
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/*
 * Note:
 *      a--z <--> 97--122
 *      A--Z <--> 65--90
 *      0--9 <--> 48--57
 */

/*
 *XOR:
 *      如果a、b两个值不相同，则异或结果为1。如果a、b两个值相同，异或结果为0。
 *拓展:
 *      BCC(Block Check Character/信息组校验码/异或校验法)
 *      CRC(Cyclic Redundancy Check/循环冗余校验)
 *      LRC(Longitudinal Redundancy Check/纵向冗余校验)
 */
char findTheDifference(char* s, char* t) {
    char tmp=0x00;
    while(*s){
        tmp=(char)(tmp^(*s));
        s++;
    }   
    while(*t){
        tmp=(char)(tmp^(*t));
        t++;
    }
return tmp;
}

