/*
Find the Difference  QuestionEditorial Solution  My Submissions
Total Accepted: 19810
Total Submissions: 39974
Difficulty: Easy
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/*
 * Note:
 *      a--z <--> 97--122
 *      A--Z <--> 65--90
 *      0--9 <--> 48--57
 */
#define OFFSET 97
#define TOTAL 26

char findTheDifference(char* s, char* t) {
    int count_s[TOTAL]={0};
    int count_t[TOTAL]={0};
    char res='\0';
    while(*s){
        count_s[((int)(*s)-OFFSET)]++;
        s++;
    }
    while(*t){
        count_t[((int)(*t)-OFFSET)]++;
        t++;
    }
    for(int i=0;i<TOTAL;i++){
        if(count_s[i]!=count_t[i]){
            res=(char)(i+OFFSET);
        }
    }
return res;
}
